import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedAnime = {
  title: string;
  summary: string;
  creator: string;
  ep_count: number;
  season: number;
  image: string;
  genre: string;

  // optional in your current seed data but required in schema
  format?: string;
  eps_dur?: string;
  studios?: string;
  producers?: string;
};

function defaultIfEmpty(value: string | undefined | null, fallback: string) {
  const v = (value ?? "").trim();
  return v.length ? v : fallback;
}

function safeName(input: string) {
  return input.replace(/\s+/g, " ").trim();
}

async function upsertStaffByName(name: string, image?: string) {
  const staffName = safeName(name);

  return prisma.staff.upsert({
    where: { name: staffName },
    update: {
      image: image ?? undefined,
    },
    create: {
      name: staffName,
      image: image ?? undefined,
    },
  });
}

async function upsertAnimeStaffCredit(args: {
  animeId: string;
  staffId: string;
  role: string;
  roleGroup?: string;
  isMain?: boolean;
  sortOrder?: number;
}) {
  return prisma.animeStaff.upsert({
    where: {
      animeId_staffId_role: {
        animeId: args.animeId,
        staffId: args.staffId,
        role: args.role,
      },
    },
    update: {
      roleGroup: args.roleGroup ?? null,
      isMain: args.isMain ?? false,
      sortOrder: args.sortOrder ?? null,
    },
    create: {
      animeId: args.animeId,
      staffId: args.staffId,
      role: args.role,
      roleGroup: args.roleGroup ?? null,
      isMain: args.isMain ?? false,
      sortOrder: args.sortOrder ?? null,
    },
  });
}

async function seedAnimeStaffForAllAnime(
  records: Array<{
    id: string;
    title: string;
    creator: string | null;
    studios: string | null;
    producers: string | null;
  }>
) {

  for (const anime of records) {
    const creator = defaultIfEmpty(anime.creator, "Unknown Creator");
    const studio = defaultIfEmpty(anime.studios, "Unknown Studio");
    const producer = defaultIfEmpty(anime.producers, "Unknown Producer");

    const director = await upsertStaffByName(`${anime.title} — Director`);
    const seriesComp = await upsertStaffByName(`${anime.title} — Series Composition`);
    const charDesign = await upsertStaffByName(`${anime.title} — Character Design`);
    const music = await upsertStaffByName(`${anime.title} — Music`);

    // Use real-ish fields as staff too (still fits AniList “Staff” model)
    const creatorStaff = await upsertStaffByName(creator);
    const studioStaff = await upsertStaffByName(studio);
    const producerStaff = await upsertStaffByName(producer);

    // Upsert credits (AniList staff page style)
    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: director.id,
      role: "Director",
      roleGroup: "Directing",
      isMain: true,
      sortOrder: 1,
    });

    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: seriesComp.id,
      role: "Series Composition",
      roleGroup: "Writing",
      isMain: true,
      sortOrder: 2,
    });

    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: charDesign.id,
      role: "Character Design",
      roleGroup: "Art",
      isMain: false,
      sortOrder: 10,
    });

    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: music.id,
      role: "Music",
      roleGroup: "Sound",
      isMain: false,
      sortOrder: 11,
    });

    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: creatorStaff.id,
      role: "Original Creator",
      roleGroup: "Writing",
      isMain: false,
      sortOrder: 12,
    });

    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: studioStaff.id,
      role: "Studio",
      roleGroup: "Production",
      isMain: false,
      sortOrder: 20,
    });

    await upsertAnimeStaffCredit({
      animeId: anime.id,
      staffId: producerStaff.id,
      role: "Producer",
      roleGroup: "Production",
      isMain: false,
      sortOrder: 21,
    });
  }
}

async function main() {
  const animeList: SeedAnime[] = [
    {
      title: "Bleach: Thousand-Year Blood War",
      summary:
        "Ichigo Kurosaki thought his life would finally calm down after earning the power and responsibility of a Soul Reaper. But when strange spiritual disturbances begin spreading through Karakura Town and beyond, it becomes clear that something far worse than Hollows is moving in the shadows. A wave of disappearances and silent killings hints at an enemy that understands Soul Reaper systems, tactics, and weaknesses—an enemy that has been waiting for the perfect moment to strike.\n\nThat moment arrives when the Quincy Empire, led by the terrifying Yhwach, declares war on Soul Society. The Wandenreich invade with ruthless precision, crushing squads, stealing Bankai, and forcing captains and lieutenants into the most desperate battles of their lives. As the Soul Reapers scramble to survive, secrets about the Quincy, the Soul King, and the true structure of the afterlife surface—revealing that the conflict isn’t just a battle for territory, but a clash over the very rules of existence.\n\nWith the Soul Society on the brink of collapse, Ichigo is pushed to confront the origin of his own power: the truths behind his Zanpakutō, his mixed spiritual heritage, and what it really means to protect people when the cost is everything. Allies are broken, loyalties are tested, and victory becomes less about strength and more about resolve. In a war where both sides believe they are restoring the world to its “proper” state, Ichigo must decide what future is worth fighting for—and what he’s willing to lose to reach it.",
      creator: "Tite Kubo",
      ep_count: 40,
      season: 3,
      image: "/assets/Anime/bleach_v2.png",
      genre: "Action, Shounen, Supernatural",
      format: "TV",
      eps_dur: "24m",
      studios: "Pierrot",
      producers: "Aniplex",
    },
    {
      title: "Jujutsu Kaisen",
      summary:
        "Yuji Itadori is an unusually strong high schooler living a simple life—until he encounters a cursed object so dangerous it draws monsters like a beacon. In a split-second decision to save others, Yuji swallows the object: one of Sukuna’s fingers. Rather than dying, he becomes the host of Ryomen Sukuna, the most feared curse in history, effectively turning Yuji into a walking disaster that the jujutsu world would rather execute than risk.\n\nTaken in by Tokyo Jujutsu High, Yuji enters a hidden society of sorcerers who exorcise curses created from human fear, grief, hatred, and regret. Under Gojo Satoru, Yuji trains beside Megumi Fushiguro and Nobara Kugisaki, learning cursed energy control and the harsh reality that saving people often means choosing who you can’t save. Missions escalate from local hauntings to encounters with special-grade curses and organized curse users, revealing a growing conspiracy aimed at overturning the balance of the jujutsu world.\n\nBut the greatest threat is inside Yuji himself. Sukuna doesn’t bargain—he waits, provokes, and searches for openings to seize control at the worst possible time. As jujutsu politics tighten around Yuji, allies question if he’s a hero or a ticking bomb. Yuji’s core struggle becomes deeply personal: he wants a “proper death” that has meaning, but every battle forces him to confront the pain of survival, the weight of responsibility, and the terrifying truth that being strong enough to protect others can also make you the most dangerous person in the room.",
      creator: "Gege Akutami",
      ep_count: 47,
      season: 3,
      image: "/assets/Anime/jjk_v2.png",
      genre: "Action, Dark Fantasy, Supernatural",
      format: "TV",
      eps_dur: "24m",
      studios: "MAPPA",
      producers: "TOHO animation",
    },
    {
      title: "Demon Slayer",
      summary:
        "Tanjiro Kamado returns home to find his family slaughtered by demons, with his sister Nezuko being the sole survivor—yet tragically transformed into a demon herself. Refusing to give up on her humanity, Tanjiro sets out on a path that is equal parts revenge and rescue: he wants to stop the demon who destroyed his life, and he wants to find a cure that will bring his sister back.\n\nTo do that, Tanjiro joins the Demon Slayer Corps, an organization that has fought demons for generations in the shadows of Japan’s night. Through brutal training, he learns breathing techniques that push the human body to its limits, sharpening his senses and swordsmanship into something capable of matching supernatural monsters. Each mission introduces Tanjiro to demons with horrifying power and heartbreaking origins—creatures shaped by despair, abuse, and the thirst for survival—forcing Tanjiro to balance compassion with the necessity of killing.\n\nAs Tanjiro grows stronger, the true scale of the war reveals itself: the Demon King Muzan Kibutsuji and his elite forces, the Twelve Kizuki, are far beyond anything most slayers can handle. Tanjiro’s journey becomes a fight against fate itself—surviving impossible battles, earning the respect of the Hashira, and uncovering the legacy behind his own family’s connection to a legendary breathing style. In a world where one mistake means death, Tanjiro pushes forward with empathy as his weapon and determination as his shield, refusing to let tragedy be the final word.",
      creator: "Koyoharu Gotouge",
      ep_count: 63,
      season: 4,
      image: "/assets/Anime/demon_slayer_v2.png",
      genre: "Action, Historical, Supernatural",
      format: "TV",
      eps_dur: "24m",
      studios: "ufotable",
      producers: "Aniplex",
    },
    {
      title: "Naruto Shippuden",
      summary:
        "After years of training with Jiraiya, Naruto Uzumaki returns to the Hidden Leaf Village no longer just the loud kid everyone ignored—he’s a shinobi with real skill, real scars, and a real dream. But his homecoming isn’t peaceful. A shadowy organization called Akatsuki is moving across the nations, hunting the Tailed Beasts and the jinchūriki who contain them. Naruto realizes quickly that his journey to become Hokage is no longer just about recognition—it’s about survival and protecting the people who finally believe in him.\n\nAs Team 7’s story continues, the series becomes a collision of personal rivalries and world-level war. Sasuke Uchiha’s path drifts further into darkness as he seeks revenge and power, while Naruto fights to bring him back without losing himself. Meanwhile, political tension between villages, secret histories of legendary clans, and the consequences of past wars all bubble to the surface. The shinobi world begins to crack under the weight of old hatred, and the line between “hero” and “villain” becomes painfully complicated.\n\nNaruto Shippuden builds toward massive turning points: heartbreaking sacrifices, brutal battles against god-level enemies, and revelations about the origins of chakra and the true meaning of peace. Naruto’s growth isn’t just strength—he learns leadership, empathy, and the burden of carrying hope when everyone else is ready to give up. In the end, it’s a story about cycles of revenge and the fight to break them—where the greatest power isn’t a jutsu, but the ability to understand someone who’s already decided to hate you.",
      creator: "Masashi Kishimoto",
      ep_count: 500,
      season: 21,
      image: "/assets/Anime/naruto.png",
      genre: "Action, Adventure, Comedy",
      format: "TV",
      eps_dur: "23m",
      studios: "Pierrot",
      producers: "TV Tokyo",
    },
    {
      title: "Solo Leveling",
      summary:
        "In a world where mysterious gates open and connect Earth to deadly dungeons, “Hunters” risk their lives to clear monsters and protect humanity. Sung Jinwoo is known as the weakest Hunter of all—barely surviving raids, constantly injured, and mocked for being useless. He keeps showing up anyway, because he needs the money to support his family and pay for his mother’s hospital care. For Jinwoo, every dungeon isn’t an adventure—it's a gamble with his life.\n\nEverything changes when a routine raid turns into a nightmare: a hidden double dungeon filled with rules, traps, and an overwhelming presence that wipes out stronger Hunters like they’re nothing. Jinwoo is left behind and should die… but instead, he receives a strange “System” that only he can see—like a game interface giving him quests, stats, and the ability to level up. For the first time ever, a Hunter can grow stronger after awakening, and Jinwoo becomes the exception that threatens to rewrite the rules of the entire world.\n\nAs Jinwoo’s power skyrockets, he’s forced into conflicts that are bigger than any single dungeon. Powerful guilds want to control him, governments want to monitor him, and the truth behind the gates begins to reveal an ancient war with cosmic stakes. Jinwoo’s rise is thrilling, but it’s also isolating—because the stronger he becomes, the less human his battles feel. The series mixes hype progression with darker questions: what does strength cost, how far would you go to protect your people, and what happens when you become the monster everyone else fears?",
      creator: "Chugong",
      ep_count: 25,
      season: 2,
      image: "/assets/Anime/solo_leveling.png",
      genre: "Action, Fantasy, Game",
      format: "TV",
      eps_dur: "24m",
      studios: "A-1 Pictures",
      producers: "Aniplex",
    },
    {
      title: "My Hero Academia",
      summary:
        "In a society where nearly everyone is born with a superpower called a Quirk, heroism is an industry—complete with rankings, agencies, brand deals, and public expectations. Izuku Midoriya grows up idolizing heroes more than anyone, studying their moves and dreaming of becoming one himself. The problem is brutal: he’s one of the rare people born Quirkless, and the world constantly reminds him that wanting something isn’t the same as being capable of it.\n\nMidoriya’s life flips when he meets his idol, All Might, the Symbol of Peace. After witnessing Midoriya’s courage in the face of real danger, All Might chooses him as his successor and passes down One For All, a legendary power that can be inherited. But gaining power doesn’t instantly make Midoriya a hero—his body can’t handle it, and every use risks destroying him from the inside. At U.A. High School, he trains alongside future legends like Bakugo and Todoroki while facing villains that threaten the stability of hero society.\n\nAs the stakes rise, the story digs deeper into what heroism really means. Villains aren’t just “bad guys”—many are products of a system that failed them. The public’s trust becomes fragile, heroes face burnout and corruption, and the line between saving people and being used as a symbol gets messy. My Hero Academia is about growth through pressure: Midoriya learning how to lead without losing his kindness, classmates discovering their own reasons to fight, and a world realizing that peace built on one person’s shoulders will eventually crack.",
      creator: "Kohei Horikoshi",
      ep_count: 170,
      season: 8,
      image: "/assets/Anime/my_hero_academia.png",
      genre: "Action, Superhero, Shounen",
      format: "TV",
      eps_dur: "24m",
      studios: "Bones",
      producers: "TOHO animation",
    },
    {
      title: "Attack on Titan",
      summary:
        "Humanity lives behind towering walls, surviving in fear of Titans—giant, mindless creatures that devour people for no apparent reason. Eren Yeager’s world shatters when a colossal Titan breaches the wall and turns his home into a slaughterhouse, killing his mother and leaving him with a single obsession: wipe every Titan off the face of the earth. Alongside Mikasa Ackerman and Armin Arlert, Eren joins the military to fight back, believing the enemy is simple and the goal is clear.\n\nBut the truth is far more horrifying than the Titans themselves. As Eren and his friends learn the reality of the world beyond the walls, the story transforms into a brutal political and ideological war. Secrets about Titan powers, hidden histories, and betrayal from within turn every victory into another question. The Survey Corps must fight not only monsters, but propaganda, corruption, and impossible choices where saving one group may doom another.\n\nAttack on Titan becomes a story about freedom, fear, and how people justify violence. Characters you trust can become enemies, and enemies can reveal reasons you never expected. With every revelation, the meaning of “monster” shifts—from Titans, to humans, to the systems that shape them. It’s intense, strategic, and tragic, constantly asking: if you had the power to protect your people, how far would you go before you became the villain in someone else’s story?",
      creator: "Hajime Isayama",
      ep_count: 87,
      season: 4,
      image: "/assets/Anime/aot.png",
      genre: "Dark Fantasy, Action, Drama",
      format: "TV",
      eps_dur: "24m",
      studios: "WIT Studio / MAPPA",
      producers: "Kodansha",
    },
    {
      title: "One Piece",
      summary:
        "Monkey D. Luffy sets sail with a ridiculous dream: to find the legendary treasure known as the One Piece and become the King of the Pirates. In a world ruled by the World Government, the Marines, and powerful pirate crews, freedom is rare and truth is dangerous. Luffy’s greatest weapon isn’t strategy or reputation—it’s his ability to attract people who’ve lost hope and make them believe in a future again.\n\nAs the Straw Hat crew grows, each member brings their own trauma, goals, and reasons for fighting. Their adventures take them across islands with completely different cultures, politics, and threats—some hilarious, some heartbreaking, and some straight-up terrifying. Under the surface, the world is tied together by a hidden history: ancient weapons, forbidden knowledge, and a century erased from the record. Every arc pushes Luffy closer to the center of a global conflict he didn’t even realize he stepped into.\n\nWhat makes One Piece hit hard is that it isn’t just about fights—it’s about inherited will, chosen family, and rebellion against systems that crush people. Luffy constantly challenges tyrants, slavers, and corrupt leaders, not because he wants to be a hero, but because he can’t stand watching someone’s freedom get stolen. The story builds into massive wars, world-shaking alliances, and reveals that turn a goofy pirate journey into one of the biggest, deepest fantasy worlds in anime.",
      creator: "Eiichiro Oda",
      ep_count: 1100,
      season: 21,
      image: "/assets/Anime/one_piece.png",
      genre: "Action, Adventure, Comedy",
      format: "TV",
      eps_dur: "24m",
      studios: "Toei Animation",
      producers: "Fuji TV",
    },
    {
      title: "Fullmetal Alchemist: Brotherhood",
      summary:
        "After attempting forbidden human transmutation to bring their mother back, brothers Edward and Alphonse Elric pay a horrifying price: Edward loses an arm and a leg, while Alphonse loses his entire body—his soul bound to a suit of armor. Determined to undo the damage, they become State Alchemists and search for the Philosopher’s Stone, a rumored artifact capable of amplifying alchemy and restoring what was lost.\n\nTheir journey quickly reveals that the Stone is tied to genocide, political manipulation, and human experimentation on a national scale. The militarized government of Amestris is built on secrets, with shady projects and “accidents” that look more like planned sacrifices. As the brothers dig deeper, they meet allies and enemies whose lives were shaped by war: soldiers with PTSD, civilians who lost everything, and survivors who refuse to let history be rewritten.\n\nBrotherhood is a story about consequences and morality. It asks what a life is worth, whether power can ever be used cleanly, and how far people will go to “fix” their pain. The villains aren’t random—they represent twisted philosophy and long-term planning. And through it all, Ed and Al learn that real strength is choosing responsibility over shortcuts, protecting others even when it costs, and accepting that some things can’t be gained without equal sacrifice.",
      creator: "Hiromu Arakawa",
      ep_count: 64,
      season: 1,
      image: "/assets/Anime/fmab.png",
      genre: "Action, Adventure, Fantasy",
      format: "TV",
      eps_dur: "24m",
      studios: "Bones",
      producers: "Aniplex",
    },
    {
      title: "Hunter x Hunter (2011)",
      summary:
        "Gon Freecss grows up believing his father abandoned him, only to learn the truth: Ging is alive and is a legendary “Hunter,” an elite class of adventurers licensed to explore dangerous lands, track rare creatures, uncover secrets, and take on missions normal people can’t survive. Gon decides to become a Hunter not for revenge, but for understanding—he wants to know what could be so amazing that his father would choose it over everything else.\n\nThe Hunter Exam introduces Gon to lifelong friends and brutal reality: talent doesn’t guarantee survival. Killua is an assassin kid trying to escape his family’s shadow, Kurapika is fueled by revenge for his massacred clan, and Leorio wants power to help people in his own way. Their paths split and intersect across arcs that feel completely different—tournament battles, crime family politics, psychological mind games, and wars against creatures that force humanity to question its own place in the food chain.\n\nHunter x Hunter shines because it doesn’t play fair. Power systems are strategic, fights are brainy, and victories often come with a cost. The story explores obsession, morality, and how good intentions can become destructive. It builds to arcs that go from fun adventure to some of the darkest, most intense storytelling in shounen—where the real question isn’t “who wins,” but “what does winning do to you afterward?”",
      creator: "Yoshihiro Togashi",
      ep_count: 148,
      season: 7,
      image: "/assets/Anime/hxh.png",
      genre: "Action, Adventure, Fantasy",
      format: "TV",
      eps_dur: "24m",
      studios: "Madhouse",
      producers: "VAP",
    },
    {
      title: "Chainsaw Man",
      summary:
        "Denji’s life is rock-bottom: he’s drowning in debt inherited from his father, surviving by hunting devils for pocket change, and living with only his pet devil-dog Pochita as family. When he’s betrayed and killed, Denji makes a contract that brings him back as Chainsaw Man—a human-devil hybrid with chainsaws bursting from his body. Suddenly, he’s thrown into the world of Public Safety, an organization that weaponizes devil hunters to fight threats that regular people can’t even comprehend.\n\nDenji’s dreams are painfully simple—good food, a bed, and someone to care about him. But that simplicity makes him easy to manipulate, and the people around him often treat him as a tool rather than a person. As Denji meets fellow hunters like Aki and Power, the story mixes chaotic comedy with sudden, brutal tragedy. Devils are born from fear, and the stronger the fear, the stronger the devil—meaning the world’s worst nightmares take physical form.\n\nChainsaw Man is about control, loneliness, and how trauma distorts desire. The fights are insane, but the emotional damage is the real threat. Denji has to figure out who he is when everyone wants something from him—his power, his loyalty, his body, his future. It’s stylish, violent, and surprisingly human, showing how someone starved of love can confuse survival with happiness until reality forces them to grow.",
      creator: "Tatsuki Fujimoto",
      ep_count: 12,
      season: 1,
      image: "/assets/Anime/chainsaw_man.png",
      genre: "Action, Dark Fantasy, Supernatural",
      format: "TV",
      eps_dur: "24m",
      studios: "MAPPA",
      producers: "Shueisha",
    },
    {
      title: "Spy x Family",
      summary:
        "In a tense Cold War-like era, master spy Twilight is tasked with an impossible mission: infiltrate an elite social circle by building a “perfect family” in a matter of days. To do it, he becomes Loid Forger, adopts a young girl named Anya, and marries a woman named Yor. The twist is that none of them are normal—Loid is a spy, Yor is a professional assassin, and Anya can read minds. And somehow… they all keep their secrets from each other.\n\nWhat starts as a fake household turns into a surprisingly wholesome (and chaotic) found-family story. Loid tries to stay emotionally detached because attachments get spies killed. Yor tries to act like a normal wife while hiding the fact that she murders people for a living. Anya just wants the family to stay together, even when she knows every secret and every lie. Missions, school politics, and assassination jobs collide with parenting stress, awkward romance, and the daily struggle of pretending to be “normal.”\n\nSpy x Family balances comedy with emotional moments about connection and healing. It’s about broken people building something real by accident. Even though their roles started as lies, their small acts—protecting each other, showing up, trying—become genuine. And in a world obsessed with suspicion and conflict, the Forgers slowly become proof that peace can start with something as simple as caring about the people in your home.",
      creator: "Tatsuya Endo",
      ep_count: 37,
      season: 2,
      image: "/assets/Anime/spy_x_family.png",
      genre: "Comedy, Action, Slice of Life",
      format: "TV",
      eps_dur: "24m",
      studios: "WIT Studio / CloverWorks",
      producers: "Shueisha",
    },
    {
      title: "Death Note",
      summary:
        "Light Yagami is a brilliant student who believes the world is rotten. When he finds a mysterious notebook—the Death Note—he discovers that anyone whose name is written inside will die. With the power to kill from anywhere, Light decides to become a godlike judge, cleansing society of criminals and creating a “perfect” world under his rule. He calls this new identity Kira, and the world begins to change as people fear judgment from an invisible executioner.\n\nBut Kira’s rise draws the attention of L, a legendary detective who treats the case like a chess match. L quickly narrows the search, and what follows is a psychological war where each side tries to expose the other without revealing themselves. Light must balance school life, family life, and constant suspicion, all while manipulating people around him to stay ahead. Meanwhile, the Death Note introduces rules, loopholes, and supernatural elements that expand the game beyond simple murder.\n\nDeath Note is less about action and more about obsession, ego, and moral collapse. It asks whether power can ever be used “cleanly,” and how quickly someone becomes what they claim to hate when they believe the ends justify the means. As the body count rises and the pressure tightens, the story becomes a warning: when someone decides they alone define justice, the line between savior and tyrant disappears.",
      creator: "Tsugumi Ohba",
      ep_count: 37,
      season: 1,
      image: "/assets/Anime/death_note.png",
      genre: "Thriller, Mystery, Supernatural",
      format: "TV",
      eps_dur: "23m",
      studios: "Madhouse",
      producers: "VAP",
    },
  ];

  const animeMap: Record<string, { id: string }> = {};
  const createdAnimeRecords: Array<{
    id: string;
    title: string;
    creator: string | null;
    studios: string | null;
    producers: string | null;
  }> = [];

  function defaultIfEmpty(value: string | undefined | null, fallback: string) {
    const v = (value ?? "").trim();
    return v.length ? v : fallback;
  }

  for (const anime of animeList) {
    const record = await prisma.anime.upsert({
      where: { title: anime.title },
      update: {
        summary: anime.summary,
        creator: anime.creator,
        ep_count: anime.ep_count,
        season: anime.season,
        image: anime.image,
        genre: anime.genre,
        format: defaultIfEmpty(anime.format, "TV"),
        eps_dur: defaultIfEmpty(anime.eps_dur, "24m"),
        studios: defaultIfEmpty(anime.studios, "Unknown Studio"),
        producers: defaultIfEmpty(anime.producers, "Unknown Producer"),
      },
      create: {
        title: anime.title,
        summary: anime.summary,
        creator: anime.creator,
        ep_count: anime.ep_count,
        season: anime.season,
        image: anime.image,
        genre: anime.genre,
        format: defaultIfEmpty(anime.format, "TV"),
        eps_dur: defaultIfEmpty(anime.eps_dur, "24m"),
        studios: defaultIfEmpty(anime.studios, "Unknown Studio"),
        producers: defaultIfEmpty(anime.producers, "Unknown Producer"),
      },
      select: {
        id: true,
        title: true,
        creator: true,
        studios: true,
        producers: true,
      },
    });

    animeMap[record.title] = { id: record.id };
    createdAnimeRecords.push(record);
  }

  const characterList = [
    // Naruto Shippuden Characters
    {
      name: "Naruto Uzumaki",
      image: "/assets/Characters/naruto.png",
      role: "Genin / Jinchuriki of Kurama",
      desc: "A loud, determined ninja who dreams of becoming Hokage and earning the village's respect.",
      stats: 95,
      abilities: "Shadow Clone Jutsu, Rasengan, Sage Mode, Kurama Chakra Mode",
      strength: "Unbreakable will, massive chakra reserves, inspires allies.",
      weakness: "Impulsive, can rush into fights without thinking.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Sasuke Uchiha",
      image: "/assets/Characters/sasuke.png",
      role: "Avenger / Leaf Shinobi",
      desc: "The last Uchiha heir who walks a dark path seeking power and revenge.",
      stats: 96,
      abilities: "Sharingan, Mangekyo Sharingan, Chidori, Amaterasu",
      strength: "Genius-level talent, deadly speed and precision.",
      weakness: "Isolates himself, consumed by vengeance.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Sakura Haruno",
      image: "/assets/Characters/sakura.png",
      role: "Medical Ninja / Tsunade's Disciple",
      desc: "A chakra-control prodigy who becomes one of the strongest medical ninjas in history.",
      stats: 92,
      abilities: "Medical Ninjutsu, Chakra-Enhanced Strength, Hundred Healings",
      strength: "Perfect chakra control, physical power, battlefield healing.",
      weakness: "Emotionally tied to teammates.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Jiraiya",
      image: "/assets/Characters/jiraiya.png",
      role: "Legendary Sannin / Toad Sage",
      desc: "A wandering sage whose legacy shapes the future of the ninja world.",
      stats: 95,
      abilities: "Sage Mode, Toad Summoning, Rasengan",
      strength: "Wisdom, versatility, powerful ninjutsu.",
      weakness: "Reckless tendencies.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Tsunade",
      image: "/assets/Characters/tsunade.png",
      role: "Fifth Hokage",
      desc: "A legendary medical ninja with monstrous strength.",
      stats: 93,
      abilities: "Medical Ninjutsu, Super Strength, Creation Rebirth",
      strength: "Healing mastery, leadership.",
      weakness: "Emotional trauma, gambling addiction.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Hinata Hyuga",
      image: "/assets/Characters/hinata.png",
      role: "Hyuga Heiress",
      desc: "A gentle but determined kunoichi who finds her strength.",
      stats: 85,
      abilities: "Byakugan, Gentle Fist",
      strength: "Perception, chakra control.",
      weakness: "Low confidence early on.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Kakashi Hatake",
      image: "/assets/Characters/kakashi.png",
      role: "Jonin / Copy Ninja",
      desc: "The Copy Ninja of the Leaf, famous for his Sharingan and calm demeanor.",
      stats: 92,
      abilities: "Sharingan, Lightning Blade, vast jutsu knowledge.",
      strength: "Battle IQ, experience, leadership.",
      weakness: "Limited stamina compared to monsters like Naruto/Sasuke.",
      animeTitle: "Naruto Shippuden",
    },
    {
      name: "Itachi Uchiha",
      image: "/assets/Characters/itachi.png",
      role: "Rogue Ninja / Former Anbu",
      desc: "A prodigy who sacrificed everything in the shadows to protect Konoha.",
      stats: 97,
      abilities: "Mangekyo Sharingan, Tsukuyomi, Amaterasu, Susanoo.",
      strength: "Calm, insanely intelligent, perfect genjutsu user.",
      weakness: "Chronic illness, carries heavy emotional burden.",
      animeTitle: "Naruto Shippuden",
    },
    // Jujutsu Kaiesen Characters
    {
      name: "Satoru Gojo",
      image: "/assets/Characters/gojo.png",
      role: "Jujutsu Sorcerer / Teacher",
      desc: "The strongest jujutsu sorcerer, casually broken and cocky.",
      stats: 99,
      abilities: "Limitless, Infinity, Hollow Purple, Six Eyes",
      strength: "Overwhelming power, near untouchable defense.",
      weakness: "Overconfident, tends to act alone.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Megumi Fushiguro",
      image: "/assets/Characters/megumi.png",
      role: "Jujutsu Sorcerer",
      desc: "A serious sorcerer with powerful shikigami and hidden potential.",
      stats: 89,
      abilities: "Ten Shadows Technique, shikigami summoning",
      strength: "Strategic fighter, adaptable in battle.",
      weakness: "Undervalues himself, can hesitate.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Yuji Itadori",
      image: "/assets/Characters/yuji.png",
      role: "Jujutsu Sorcerer / Sukuna's Vessel",
      desc: "A compassionate teenager thrust into the jujutsu world after becoming the host of Ryomen Sukuna.",
      stats: 92,
      abilities: "Enhanced strength, Divergent Fist, Black Flash, Sukuna possession",
      strength: "Physical durability, empathy, unbreakable resolve.",
      weakness: "Lacks refined cursed techniques, emotionally vulnerable.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Nobara Kugisaki",
      image: "/assets/Characters/nobara.png",
      role: "Jujutsu Sorcerer",
      desc: "A fierce and unapologetic sorcerer who fights using cursed tools and precision.",
      stats: 88,
      abilities: "Straw Doll Technique, Resonance, Hairpin",
      strength: "Mental toughness, precision attacks.",
      weakness: "Close-range vulnerability.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Kento Nanami",
      image: "/assets/Characters/nanami.png",
      role: "Grade 1 Jujutsu Sorcerer",
      desc: "A former salaryman who values efficiency and responsibility above heroics.",
      stats: 93,
      abilities: "Ratio Technique, Black Flash",
      strength: "Discipline, battle composure.",
      weakness: "Burnout, emotional repression.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Maki Zenin",
      image: "/assets/Characters/maki.png",
      role: "Jujutsu Sorcerer / Zenin Clan Outcast",
      desc: "A weapon master born without cursed energy who defies sorcerer norms.",
      stats: 94,
      abilities: "Heavenly Restriction, cursed weapon mastery",
      strength: "Physical power, relentless will.",
      weakness: "Clan persecution.",
      animeTitle: "Jujutsu Kaisen",
    },
    // Curses Villains
    {
      name: "Ryomen Sukuna",
      image: "/assets/Characters/sukuna.png",
      role: "King of Curses",
      desc: "An ancient and sadistic curse whose power terrifies even elite sorcerers.",
      stats: 100,
      abilities: "Dismantle, Cleave, Domain Expansion (Malevolent Shrine)",
      strength: "Godlike cursed energy, battle dominance.",
      weakness: "Arrogance, relies on vessels.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Suguru Geto",
      image: "/assets/Characters/geto.png",
      role: "Curse User / Ideologue",
      desc: "A former sorcerer whose twisted beliefs lead him to oppose humanity.",
      stats: 95,
      abilities: "Cursed Spirit Manipulation",
      strength: "Large-scale curse control.",
      weakness: "Ideological obsession.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Mahito",
      image: "/assets/Characters/mahito.png",
      role: "Special Grade Curse",
      desc: "A cruel curse fascinated by the shape and fragility of the human soul.",
      stats: 94,
      abilities: "Idle Transfiguration, Domain Expansion (Self-Embodiment of Perfection)",
      strength: "Soul manipulation, adaptability.",
      weakness: "Overconfidence.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Toji Fushiguro",
      image: "/assets/Characters/toji.png",
      role: "Sorcerer Killer",
      desc: "A legendary assassin with no cursed energy who hunts sorcerers.",
      stats: 96,
      abilities: "Heavenly Restriction, cursed weapon mastery",
      strength: "Extreme speed, combat instincts.",
      weakness: "Lack of cursed techniques.",
      animeTitle: "Jujutsu Kaisen",
    },
    {
      name: "Choso",
      image: "/assets/Characters/choso.png",
      role: "Death Painting Womb",
      desc: "A cursed-human hybrid driven by loyalty to his brothers.",
      stats: 92,
      abilities: "Blood Manipulation, Piercing Blood",
      strength: "Endurance, battlefield control.",
      weakness: "Emotional attachments.",
      animeTitle: "Jujutsu Kaisen",
    },


    {
      name: "Tanjiro Kamado",
      image: "/assets/Characters/tanjiro.png",
      role: "Demon Slayer",
      desc: "A kind-hearted boy who becomes a Demon Slayer after tragedy hits his family.",
      stats: 90,
      abilities: "Water Breathing, Sun Breathing, enhanced smell",
      strength: "Empathy, strong resolve, quick learner.",
      weakness: "Pushes himself past his limits, gets injured often.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Nezuko Kamado",
      image: "/assets/Characters/nezuko.png",
      role: "Demon / Tanjiro’s Sister",
      desc: "A demon who retains her humanity and fights to protect others.",
      stats: 91,
      abilities: "Blood Demon Art, explosive blood, demon regeneration",
      strength: "Raw power, resilience, emotional bond with Tanjiro.",
      weakness: "Limited speech, sunlight vulnerability (early).",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Inosuke Hashibira",
      image: "/assets/Characters/inosuke.png",
      role: "Demon Slayer",
      desc: "A feral and aggressive fighter raised in the mountains.",
      stats: 90,
      abilities: "Beast Breathing, flexible body",
      strength: "Instinctual combat, pain tolerance.",
      weakness: "Reckless behavior.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Kyojuro Rengoku",
      image: "/assets/Characters/rengoku.png",
      role: "Flame Hashira",
      desc: "A bright, passionate Hashira who fights with unwavering conviction.",
      stats: 94,
      abilities: "Flame Breathing, incredible physical strength",
      strength: "Unshakable spirit, inspires everyone around him.",
      weakness: "Tends to shoulder everything himself.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Giyu Tomioka",
      image: "/assets/Characters/giyu.png",
      role: "Water Hashira",
      desc: "A stoic swordsman who introduces Tanjiro to the Demon Slayer Corps.",
      stats: 94,
      abilities: "Water Breathing, Dead Calm",
      strength: "Precision, calm decision-making.",
      weakness: "Emotional isolation.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Tengen Uzui",
      image: "/assets/Characters/tengen.png",
      role: "Sound Hashira",
      desc: "A flamboyant ninja turned Demon Slayer who values flash and flair.",
      stats: 93,
      abilities: "Sound Breathing, explosive techniques",
      strength: "Speed, battlefield awareness.",
      weakness: "Poison vulnerability.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Akaza",
      image: "/assets/Characters/akaza.png",
      role: "Upper Rank Three",
      desc: "A battle-hungry demon who respects strength above all else.",
      stats: 97,
      abilities: "Destructive Death, Compass Needle",
      strength: "Martial mastery, relentless combat.",
      weakness: "Emotional trauma.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Kokushibo",
      image: "/assets/Characters/kokushibo.png",
      role: "Upper Rank One",
      desc: "The strongest of the Twelve Kizuki and a former Demon Slayer whose obsession with power consumed him.",
      stats: 99,
      abilities: "Moon Breathing, Blood Demon Art, enhanced regeneration, transparent world",
      strength: "Unmatched swordsmanship, battle experience, overwhelming presence.",
      weakness: "Inner conflict, fractured identity, attachment to his past.",
      animeTitle: "Demon Slayer",
    },
    {
      name: "Doma",
      image: "/assets/Characters/doma.png",
      role: "Upper Rank Two",
      desc: "A charismatic and cruel demon who hides his complete lack of empathy behind a friendly facade.",
      stats: 98,
      abilities: "Ice Blood Demon Art, cryokinesis, absorption",
      strength: "Wide-area control, emotional manipulation, rapid regeneration.",
      weakness: "Arrogance, emotional emptiness, underestimates opponents.",
      animeTitle: "Demon Slayer",
    },
    // My Hero Acadamia
    {
      name: "Izuku Midoriya",
      image: "/assets/Characters/izuku.png",
      role: "Hero Student",
      desc: "A quirkless boy who inherits One For All and trains to become the greatest hero.",
      stats: 91,
      abilities: "One For All, super strength, Full Cowling",
      strength: "Analytical, determined, never gives up.",
      weakness: "Overthinks, can push his body too far.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Katsuki Bakugo",
      image: "/assets/Characters/bakugo.png",
      role: "Hero Student",
      desc: "An explosive prodigy driven by pride and relentless ambition.",
      stats: 93,
      abilities: "Explosion, advanced combat mobility",
      strength: "Raw power, battle instincts.",
      weakness: "Short temper, emotional rigidity.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Shoto Todoroki",
      image: "/assets/Characters/todoroki.png",
      role: "Hero Student",
      desc: "A gifted student wielding both fire and ice.",
      stats: 92,
      abilities: "Half-Cold Half-Hot, advanced elemental control",
      strength: "Versatility, battlefield control.",
      weakness: "Emotional trauma, internal conflict.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Ochaco Uraraka",
      image: "/assets/Characters/uraraka.png",
      role: "Hero Student",
      desc: "A determined student who fights to support her family.",
      stats: 88,
      abilities: "Zero Gravity, martial arts",
      strength: "Mobility, creativity.",
      weakness: "Motion sickness.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Mirio Togata",
      image: "/assets/Characters/mirio.png",
      role: "Pro Hero / Big Three",
      desc: "A cheerful hero whose mastery of Permeation makes him nearly unstoppable.",
      stats: 95,
      abilities: "Permeation, elite combat skills",
      strength: "Combat IQ, perseverance.",
      weakness: "Quirk complexity.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "All Might",
      image: "/assets/Characters/all_might.png",
      role: "Symbol of Peace / Former No.1 Hero",
      desc: "The legendary hero who upheld peace and passed his power to Midoriya.",
      stats: 98,
      abilities: "One For All, superhuman strength, speed",
      strength: "Inspiration, overwhelming power.",
      weakness: "Severely injured body, time limit.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Endeavor",
      image: "/assets/Characters/endeavor.png",
      role: "No.1 Pro Hero",
      desc: "A ruthless hero obsessed with surpassing All Might.",
      stats: 96,
      abilities: "Hellflame, high-temperature combat",
      strength: "Raw power, determination.",
      weakness: "Emotional damage, strained family ties.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Aizawa",
      image: "/assets/Characters/aizawa.png",
      role: "UA Teacher / Pro Hero Eraser Head",
      desc: "A strict but caring teacher who nullifies Quirks.",
      stats: 91,
      abilities: "Erasure, capture weapon mastery",
      strength: "Tactical awareness, support utility.",
      weakness: "Physical strain, dry eyes.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Tomura Shigaraki",
      image: "/assets/Characters/tomura.png",
      role: "League of Villains Leader",
      desc: "A destructive villain shaped by trauma and manipulation.",
      stats: 97,
      abilities: "Decay, enhanced regeneration, All For One",
      strength: "Mass destruction, evolving power.",
      weakness: "Mental instability.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "All For One",
      image: "/assets/Characters/all_for_one.png",
      role: "Ultimate Villain",
      desc: "A mastermind who steals and distributes Quirks.",
      stats: 99,
      abilities: "Quirk theft, enhanced strength, longevity",
      strength: "Strategic genius, overwhelming power.",
      weakness: "Arrogance, reliance on successors.",
      animeTitle: "My Hero Academia",
    },
    {
      name: "Dabi",
      image: "/assets/Characters/dabi.png",
      role: "League of Villains / Todoroki Family",
      desc: "A sadistic villain wielding unstable blue flames.",
      stats: 95,
      abilities: "Blueflame, high-output combustion",
      strength: "Destructive firepower.",
      weakness: "Self-destructive quirk.",
      animeTitle: "My Hero Academia",
    },
    // Attack on Titan
    {
      name: "Eren Yeager",
      image: "/assets/Characters/eren.png",
      role: "Attack Titan / Founding Titan",
      desc: "A determined boy whose desire for freedom drives him to reshape the world.",
      stats: 97,
      abilities: "Attack Titan, Founding Titan, War Hammer Titan, future memories",
      strength: "Unbreakable will, combat adaptability, strategic evolution.",
      weakness: "Obsessive ideology, emotional isolation.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Mikasa Ackerman",
      image: "/assets/Characters/mikasa.png",
      role: "Elite Soldier / Ackerman",
      desc: "A genetically gifted warrior devoted to protecting Eren.",
      stats: 96,
      abilities: "ODM mastery, Ackerman combat instincts",
      strength: "Speed, precision, loyalty.",
      weakness: "Emotional attachment.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Armin Arlert",
      image: "/assets/Characters/armin.png",
      role: "Colossal Titan / Strategist",
      desc: "A brilliant tactician whose mind proves as powerful as any titan.",
      stats: 93,
      abilities: "Colossal Titan, battlefield strategy",
      strength: "Intelligence, moral reasoning.",
      weakness: "Self-doubt.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Levi Ackerman",
      image: "/assets/Characters/levi.png",
      role: "Captain / Humanity’s Strongest Soldier",
      desc: "A relentless and precise captain feared by both titans and humans.",
      stats: 98,
      abilities: "ODM mastery, Ackerman reflexes",
      strength: "Combat efficiency, discipline.",
      weakness: "Physical exhaustion, trauma.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Erwin Smith",
      image: "/assets/Characters/erwin.png",
      role: "Commander / Survey Corps",
      desc: "A visionary leader willing to sacrifice everything for truth.",
      stats: 95,
      abilities: "Strategic command, battlefield leadership",
      strength: "Charisma, resolve.",
      weakness: "Self-destructive ambition.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Hange Zoe",
      image: "/assets/Characters/hange.png",
      role: "Commander / Titan Researcher",
      desc: "An eccentric scientist driven by curiosity and responsibility.",
      stats: 90,
      abilities: "Titan research, adaptive leadership",
      strength: "Creativity, analytical thinking.",
      weakness: "Overzealous curiosity.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Reiner Braun",
      image: "/assets/Characters/reiner.png",
      role: "Armored Titan / Warrior",
      desc: "A tragic soldier torn between duty and guilt.",
      stats: 94,
      abilities: "Armored Titan, endurance combat",
      strength: "Durability, battlefield experience.",
      weakness: "Severe psychological trauma.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Bertholdt Hoover",
      image: "/assets/Characters/bertholdt.png",
      role: "Colossal Titan",
      desc: "A quiet warrior burdened by his destructive power.",
      stats: 92,
      abilities: "Colossal Titan, massive explosion",
      strength: "Raw destructive capability.",
      weakness: "Indecisiveness.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Annie Leonhart",
      image: "/assets/Characters/annie.png",
      role: "Female Titan / Warrior",
      desc: "A skilled fighter hiding deadly secrets.",
      stats: 93,
      abilities: "Female Titan, martial arts mastery",
      strength: "Precision, combat skill.",
      weakness: "Emotional detachment.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Zeke Yeager",
      image: "/assets/Characters/zeke.png",
      role: "Beast Titan / Marley Commander",
      desc: "A calculating antagonist driven by twisted compassion.",
      stats: 96,
      abilities: "Beast Titan, spinal fluid control",
      strength: "Strategic planning, ranged combat.",
      weakness: "Ideological extremism.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Historia Reiss",
      image: "/assets/Characters/historia.png",
      role: "Queen of the Walls",
      desc: "A reluctant ruler who grows into her responsibility.",
      stats: 85,
      abilities: "Political authority, royal lineage",
      strength: "Moral courage.",
      weakness: "Inexperience.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Gabi Braun",
      image: "/assets/Characters/gabi.png",
      role: "Warrior Candidate",
      desc: "A fiercely loyal soldier shaped by propaganda and war.",
      stats: 89,
      abilities: "Marksmanship, combat instincts",
      strength: "Adaptability, determination.",
      weakness: "Impulsiveness.",
      animeTitle: "Attack on Titan",
    },
    {
      name: "Falco Grice",
      image: "/assets/Characters/falco.png",
      role: "Warrior Candidate / Jaw Titan",
      desc: "A compassionate soldier who becomes a titan shifter.",
      stats: 88,
      abilities: "Jaw Titan, aerial combat",
      strength: "Empathy, adaptability.",
      weakness: "Inexperience.",
      animeTitle: "Attack on Titan",
    },
    // Bleach Characters 
    {
      name: "Ichigo Kurosaki",
      image: "/assets/Characters/ichigo.png",
      role: "Substitute Soul Reaper / Quincy-Hybrid",
      desc: "A human with the powers of a Soul Reaper, Hollow, and Quincy who stands at the center of the war.",
      stats: 98,
      abilities: "Zangetsu, Bankai, Hollowfication, Quincy abilities",
      strength: "Hybrid power, adaptability, overwhelming resolve.",
      weakness: "Emotional burden, reckless self-sacrifice.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Orihime Inoue",
      image: "/assets/Characters/orihime.png",
      role: "Healer / Human with Fullbring",
      desc: "A gentle but powerful ally whose abilities can reject reality itself.",
      stats: 90,
      abilities: "Shun Shun Rikka, reality rejection, advanced healing",
      strength: "Defensive power, compassion, resilience.",
      weakness: "Self-doubt, reluctance to fight.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Yasutora Sado",
      image: "/assets/Characters/chad.png",
      role: "Fullbringer / Brawler",
      desc: "A loyal and stoic fighter whose strength protects those he cares about.",
      stats: 92,
      abilities: "Brazo Derecha del Gigante, Brazo Izquierda del Diablo",
      strength: "Physical power, unwavering loyalty.",
      weakness: "Limited ranged capability.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },

    {
      name: "Rukia Kuchiki",
      image: "/assets/Characters/rukia.png",
      role: "Soul Reaper / Noble of the Kuchiki Clan",
      desc: "A disciplined Soul Reaper whose growth culminates in mastering her icy Zanpakutō.",
      stats: 92,
      abilities: "Sode no Shirayuki, Bankai: Hakka no Togame",
      strength: "Precision, composure under pressure.",
      weakness: "Can be emotionally reserved.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Renji Abarai",
      image: "/assets/Characters/renji.png",
      role: "Lieutenant / Soul Reaper",
      desc: "A fierce warrior who unlocks the true name of his Zanpakutō.",
      stats: 93,
      abilities: "Zabimaru, Bankai: Sōō Zabimaru",
      strength: "Raw power, loyalty.",
      weakness: "Hot-headed nature.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Byakuya Kuchiki",
      image: "/assets/Characters/byakuya.png",
      role: "Captain of Squad 6",
      desc: "A proud noble captain who redefines his ideals through defeat and rebirth.",
      stats: 95,
      abilities: "Senbonzakura, Bankai mastery",
      strength: "Elegance, tactical control.",
      weakness: "Rigid adherence to duty.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Sōsuke Aizen",
      image: "/assets/Characters/aizen.png",
      role: "Former Captain / Mastermind",
      desc: "A genius manipulator whose intellect and power rival gods, imprisoned yet pivotal in the Quincy war.",
      stats: 100,
      abilities: "Kyōka Suigetsu, Hōgyoku-enhanced immortality, advanced kido",
      strength: "Perfect hypnosis, strategic brilliance, overwhelming reiatsu.",
      weakness: "Arrogance, god complex.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Gin Ichimaru",
      image: "/assets/Characters/gin.png",
      role: "Former Captain / Assassin",
      desc: "A deceptive and soft-spoken killer whose loyalty hides a final act of rebellion.",
      stats: 95,
      abilities: "Shinsō, Kamishini no Yari",
      strength: "Deadly precision, emotional restraint.",
      weakness: "Self-destructive devotion.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Kaname Tōsen",
      image: "/assets/Characters/tosen.png",
      role: "Former Captain / Justice Seeker",
      desc: "A blind warrior who pursued justice at the cost of his humanity.",
      stats: 93,
      abilities: "Suzumushi, Bankai: Enma Kōrogi",
      strength: "Conviction, sensory combat.",
      weakness: "Rigid worldview.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },

    {
      name: "Toshiro Hitsugaya",
      image: "/assets/Characters/toshiro.png",
      role: "Captain of Squad 10",
      desc: "A prodigy captain wielding the strongest ice-type Zanpakutō.",
      stats: 94,
      abilities: "Hyōrinmaru, Mature Bankai form",
      strength: "Elemental control, growth potential.",
      weakness: "Limited stamina when overextended.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Kenpachi Zaraki",
      image: "/assets/Characters/kenpachi.png",
      role: "Captain of Squad 11",
      desc: "A battle-obsessed captain who lives solely for combat.",
      stats: 99,
      abilities: "Nozarashi, Shikai and Bankai",
      strength: "Overwhelming raw power.",
      weakness: "Lack of restraint.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Yamamoto Genryusai",
      image: "/assets/Characters/yamamoto.png",
      role: "Captain-Commander",
      desc: "The legendary founder of the Gotei 13 and master of flame.",
      stats: 100,
      abilities: "Ryūjin Jakka, Bankai: Zanka no Tachi",
      strength: "Unmatched destructive power.",
      weakness: "Rigid pride, age.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Urahara Kisuke",
      image: "/assets/Characters/urahara.png",
      role: "Former Captain / Scientist",
      desc: "A brilliant strategist whose intellect rivals his combat ability.",
      stats: 96,
      abilities: "Benihime, Bankai: Kannonbiraki Benihime Aratame",
      strength: "Unpredictability, intelligence.",
      weakness: "Over-relies on gambles.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Yhwach",
      image: "/assets/Characters/yhwach.png",
      role: "Quincy King",
      desc: "The progenitor of the Quincy and the final enemy of Soul Society.",
      stats: 100,
      abilities: "The Almighty, Auswählen, future manipulation",
      strength: "Godlike foresight and power.",
      weakness: "Overconfidence in destiny.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Jugram Haschwalth",
      image: "/assets/Characters/jugram.png",
      role: "Grandmaster of the Sternritter",
      desc: "Yhwach’s other half, embodying balance and judgment.",
      stats: 97,
      abilities: "Balance Schrift, fate redistribution",
      strength: "Absolute counter-force.",
      weakness: "Blind loyalty.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Uryu Ishida",
      image: "/assets/Characters/uryu.png",
      role: "Quincy / Sternritter",
      desc: "A conflicted Quincy walking a dangerous path between loyalty and rebellion.",
      stats: 94,
      abilities: "Antithesis Schrift, advanced Quincy techniques",
      strength: "Precision, adaptability.",
      weakness: "Internal conflict.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Bazz-B",
      image: "/assets/Characters/bazz_b.png",
      role: "Sternritter",
      desc: "A hot-headed Quincy wielding explosive flames.",
      stats: 92,
      abilities: "Burner Finger, fire manipulation",
      strength: "High-output offense.",
      weakness: "Impulsiveness.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    {
      name: "Askin Nakk Le Vaar",
      image: "/assets/Characters/askin.png",
      role: "Elite Sternritter",
      desc: "A lethal opponent who manipulates lethal dosage.",
      stats: 95,
      abilities: "Deathdealing, poison immunity",
      strength: "Hax-based combat.",
      weakness: "Arrogance.",
      animeTitle: "Bleach: Thousand-Year Blood War",
    },
    // Solo Leveling Characters
    {
      name: "Sung Jinwoo",
      image: "/assets/Characters/jinwoo.png",
      role: "Shadow Monarch / S-Rank Hunter",
      desc: "Once the weakest hunter, Jinwoo rises to become humanity’s strongest weapon.",
      stats: 100,
      abilities: "Shadow Extraction, Shadow Exchange, Monarch’s Domain, necromancy",
      strength: "Infinite growth, absolute battlefield control.",
      weakness: "Emotional isolation, overwhelming responsibility.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Cha Hae-In",
      image: "/assets/Characters/cha_haein.png",
      role: "S-Rank Hunter",
      desc: "A powerful swordswoman sensitive to mana who is drawn to Jinwoo’s presence.",
      stats: 94,
      abilities: "Enhanced speed, sword mastery",
      strength: "Precision, mana sensitivity.",
      weakness: "Overexertion.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Yoo Jinho",
      image: "/assets/Characters/jinho.png",
      role: "Vice Guild Master",
      desc: "Jinwoo’s loyal ally and business partner.",
      stats: 82,
      abilities: "Support skills, leadership",
      strength: "Loyalty, strategic thinking.",
      weakness: "Low combat power.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Go Gunhee",
      image: "/assets/Characters/go_gunhee.png",
      role: "Chairman of Korean Hunters Association",
      desc: "A wise leader who recognizes Jinwoo’s potential early.",
      stats: 88,
      abilities: "Authority, latent combat strength",
      strength: "Leadership, experience.",
      weakness: "Old age.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Baek Yoonho",
      image: "/assets/Characters/baek_yoonho.png",
      role: "S-Rank Hunter / White Tiger Guild Master",
      desc: "A fierce hunter who transforms into a beast.",
      stats: 93,
      abilities: "Beast Transformation, super strength",
      strength: "Raw power, intimidation.",
      weakness: "Limited control in beast form.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Choi Jong-In",
      image: "/assets/Characters/choi.png",
      role: "S-Rank Hunter / Mage",
      desc: "Korea’s top fire mage known for overwhelming spell output.",
      stats: 92,
      abilities: "Fire magic, large-scale destruction",
      strength: "Area control, ranged combat.",
      weakness: "Low close-range defense.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Thomas Andre",
      image: "/assets/Characters/andre.png",
      role: "National-Level Hunter",
      desc: "One of the strongest hunters in the world and leader of the Scavenger Guild.",
      stats: 98,
      abilities: "Super strength, reinforcement",
      strength: "Physical dominance.",
      weakness: "Overconfidence.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Beru",
      image: "/assets/Characters/beru.png",
      role: "Shadow Soldier / Ant King",
      desc: "A loyal and terrifying shadow born from the Jeju Island raid.",
      stats: 97,
      abilities: "Flight, regeneration, shadow combat",
      strength: "Absolute loyalty, ferocity.",
      weakness: "Overzealous devotion.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Igris",
      image: "/assets/Characters/igris.png",
      role: "Shadow Knight",
      desc: "A disciplined shadow soldier who serves as Jinwoo’s right hand.",
      stats: 95,
      abilities: "Sword mastery, enhanced agility",
      strength: "Precision, discipline.",
      weakness: "Strict adherence to orders.",
      animeTitle: "Solo Leveling",
    },
    {
      name: "Ashborn",
      image: "/assets/Characters/ashborn.png",
      role: "Original Shadow Monarch",
      desc: "The former ruler who passes his power to Jinwoo.",
      stats: 99,
      abilities: "Shadow authority, monarch’s dominion",
      strength: "Absolute command of shadows.",
      weakness: "Fading existence.",
      animeTitle: "Solo Leveling",
    },
    // One Piece Characters 
    {
      name: "Monkey D. Luffy",
      image: "/assets/Characters/luffy.png",
      role: "Captain of the Straw Hat Pirates",
      desc: "A rubber-bodied pirate driven by freedom and the dream of becoming King of the Pirates.",
      stats: 100,
      abilities: "Gomu Gomu no Mi (Hito Hito no Mi: Nika), Haki, Gear Fifth",
      strength: "Unbreakable will, limitless creativity, leadership.",
      weakness: "Reckless, emotionally driven.",
      animeTitle: "One Piece",
    },
    {
      name: "Roronoa Zoro",
      image: "/assets/Characters/zoro.png",
      role: "Combatant / Swordsman",
      desc: "A master swordsman who aims to become the greatest in the world.",
      stats: 97,
      abilities: "Three-Sword Style, Advanced Armament Haki, Asura",
      strength: "Endurance, killing intent, loyalty.",
      weakness: "Poor sense of direction.",
      animeTitle: "One Piece",
    },
    {
      name: "Nami",
      image: "/assets/Characters/nami.png",
      role: "Navigator",
      desc: "A brilliant navigator obsessed with maps, money, and survival.",
      stats: 88,
      abilities: "Clima-Tact, weather manipulation",
      strength: "Navigation skills, tactical thinking.",
      weakness: "Low physical durability.",
      animeTitle: "One Piece",
    },
    {
      name: "Usopp",
      image: "/assets/Characters/usopp.png",
      role: "Sniper",
      desc: "A sharpshooter whose courage grows stronger with every battle.",
      stats: 85,
      abilities: "Sniping, Observation Haki",
      strength: "Creativity, long-range combat.",
      weakness: "Fear under pressure.",
      animeTitle: "One Piece",
    },
    {
      name: "Sanji",
      image: "/assets/Characters/sanji.png",
      role: "Cook / Combatant",
      desc: "A chivalrous fighter whose kicks burn hotter than fire.",
      stats: 96,
      abilities: "Diable Jambe, Germa enhancements, Observation Haki",
      strength: "Speed, aerial combat.",
      weakness: "Code against harming women.",
      animeTitle: "One Piece",
    },
    {
      name: "Tony Tony Chopper",
      image: "/assets/Characters/chopper.png",
      role: "Doctor",
      desc: "A reindeer who ate the Human-Human Fruit and became a doctor.",
      stats: 84,
      abilities: "Hito Hito no Mi, Monster Point",
      strength: "Medical expertise, versatility.",
      weakness: "Naivety.",
      animeTitle: "One Piece",
    },
    {
      name: "Nico Robin",
      image: "/assets/Characters/robin.png",
      role: "Archaeologist",
      desc: "A survivor who can read the Poneglyphs and uncover the world’s history.",
      stats: 91,
      abilities: "Hana Hana no Mi, Demonio Fleur",
      strength: "Intelligence, battlefield control.",
      weakness: "Emotional trauma.",
      animeTitle: "One Piece",
    },
    {
      name: "Franky",
      image: "/assets/Characters/franky.png",
      role: "Shipwright",
      desc: "A cyborg shipwright who built the Thousand Sunny.",
      stats: 90,
      abilities: "Cyborg weaponry, General Franky",
      strength: "Durability, firepower.",
      weakness: "High cola consumption.",
      animeTitle: "One Piece",
    },
    {
      name: "Brook",
      image: "/assets/Characters/brook.png",
      role: "Musician / Swordsman",
      desc: "A living skeleton revived by the power of the Revive-Revive Fruit.",
      stats: 89,
      abilities: "Soul Solid, Yomi Yomi no Mi",
      strength: "Speed, soul-based attacks.",
      weakness: "Fragile bones (ironically).",
      animeTitle: "One Piece",
    },
    {
      name: "Jinbe",
      image: "/assets/Characters/jinbe.png",
      role: "Helmsman / Fish-Man Karate Master",
      desc: "A former Warlord who embodies honor and calm strength.",
      stats: 95,
      abilities: "Fish-Man Karate, Armament Haki",
      strength: "Defensive mastery, composure.",
      weakness: "Limited mobility on land.",
      animeTitle: "One Piece",
    },
    {
      name: "Shanks",
      image: "/assets/Characters/shanks.png",
      role: "Yonko / Red-Haired Pirates Captain",
      desc: "A legendary pirate whose presence alone commands respect.",
      stats: 99,
      abilities: "Advanced Conqueror’s Haki",
      strength: "Haki dominance, influence.",
      weakness: "Unknown full capabilities.",
      animeTitle: "One Piece",
    },
    // Full Metal Characters
    {
      name: "Edward Elric",
      image: "/assets/Characters/edward.png",
      role: "State Alchemist / Fullmetal Alchemist",
      desc: "A prodigy alchemist searching for the Philosopher’s Stone to restore what he and his brother lost.",
      stats: 94,
      abilities: "Alchemy without transmutation circles, automail combat",
      strength: "Intelligence, adaptability, moral conviction.",
      weakness: "Impulsiveness, emotional sensitivity.",
      animeTitle: "Fullmetal Alchemist: Brotherhood",
    },
    {
      name: "Alphonse Elric",
      image: "/assets/Characters/alphonse.png",
      role: "Soul-Bound Alchemist",
      desc: "Edward’s younger brother whose soul is bound to a suit of armor.",
      stats: 92,
      abilities: "Advanced alchemy, martial arts",
      strength: "Kindness, composure, resilience.",
      weakness: "Physical vulnerability of the soul seal.",
      animeTitle: "Fullmetal Alchemist: Brotherhood",
    },
    {
      name: "Roy Mustang",
      image: "/assets/Characters/roy.png",
      role: "State Alchemist / Flame Alchemist",
      desc: "A calculating officer who plans to reform the corrupt military from within.",
      stats: 95,
      abilities: "Flame alchemy, battlefield command",
      strength: "Strategic mind, overwhelming offense.",
      weakness: "Requires ignition gloves, emotional rage.",
      animeTitle: "Fullmetal Alchemist: Brotherhood",
    },
    {
      name: "Riza Hawkeye",
      image: "/assets/Characters/riza.png",
      role: "Military Sniper",
      desc: "A disciplined sharpshooter and Mustang’s most trusted ally.",
      stats: 90,
      abilities: "Marksmanship, tactical support",
      strength: "Loyalty, precision.",
      weakness: "Non-alchemist.",
      animeTitle: "Fullmetal Alchemist: Brotherhood",
    },
    {
      name: "Scar",
      image: "/assets/Characters/scar.png",
      role: "Avenger / Warrior Monk",
      desc: "A survivor of genocide whose vengeance evolves into purpose.",
      stats: 93,
      abilities: "Deconstruction alchemy, combat endurance",
      strength: "Raw power, resolve.",
      weakness: "Tunnel vision driven by anger.",
      animeTitle: "Fullmetal Alchemist: Brotherhood",
    },
    {
      name: "Father",
      image: "/assets/Characters/father.png",
      role: "Primary Antagonist",
      desc: "An ancient being seeking godhood through sacrifice.",
      stats: 98,
      abilities: "Philosopher’s Stone manipulation, energy control",
      strength: "Immense power, long-term planning.",
      weakness: "Arrogance, emotional emptiness.",
      animeTitle: "Fullmetal Alchemist: Brotherhood",
    },
    // Hunter x Hunter
    {
      name: "Gon Freecss",
      image: "/assets/Characters/gon.png",
      role: "Hunter / Nen User",
      desc: "A cheerful boy whose innocence hides terrifying resolve.",
      stats: 92,
      abilities: "Nen, Jajanken, enhanced senses",
      strength: "Determination, adaptability.",
      weakness: "Emotional volatility.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Killua Zoldyck",
      image: "/assets/Characters/killua.png",
      role: "Assassin / Hunter",
      desc: "A prodigy assassin breaking free from his family’s control.",
      stats: 95,
      abilities: "Nen, Godspeed, assassination techniques",
      strength: "Speed, combat instincts.",
      weakness: "Emotional dependence on Gon.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Kurapika",
      image: "/assets/Characters/kurapika.png",
      role: "Hunter / Nen Specialist",
      desc: "The last survivor of the Kurta Clan, driven by revenge.",
      stats: 94,
      abilities: "Nen chains, Emperor Time",
      strength: "Strategic intelligence, deadly precision.",
      weakness: "Shortened lifespan due to Emperor Time.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Leorio Paradinight",
      image: "/assets/Characters/leorio.png",
      role: "Hunter / Medical Student",
      desc: "A hot-headed but compassionate future doctor.",
      stats: 85,
      abilities: "Nen-enhanced strikes",
      strength: "Loyalty, emotional intelligence.",
      weakness: "Limited combat experience.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Hisoka Morow",
      image: "/assets/Characters/hisoka.png",
      role: "Antagonist / Nen User",
      desc: "A sadistic fighter obsessed with strong opponents.",
      stats: 96,
      abilities: "Bungee Gum, Texture Surprise",
      strength: "Unpredictability, combat creativity.",
      weakness: "Battle lust.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Chrollo Lucilfer",
      image: "/assets/Characters/chrollo.png",
      role: "Phantom Troupe Leader",
      desc: "A calm and philosophical criminal mastermind.",
      stats: 97,
      abilities: "Skill Hunter, stolen Nen abilities",
      strength: "Tactical brilliance, versatility.",
      weakness: "Attachment to his troupe.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Meruem",
      image: "/assets/Characters/meruem.png",
      role: "Chimera Ant King",
      desc: "A being born to rule who discovers humanity.",
      stats: 100,
      abilities: "Nen mastery, superhuman strength, adaptation",
      strength: "Absolute power, rapid evolution.",
      weakness: "Emotional awakening.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    {
      name: "Netero",
      image: "/assets/Characters/netero.png",
      role: "Chairman of the Hunter Association",
      desc: "A legendary martial artist who embodies human potential.",
      stats: 99,
      abilities: "100-Type Guanyin Bodhisattva",
      strength: "Speed, experience, indomitable will.",
      weakness: "Aging body.",
      animeTitle: "Hunter x Hunter (2011)",
    },
    // Chainsaw man
    {
      name: "Denji",
      image: "/assets/Characters/denji.png",
      role: "Devil Hunter / Chainsaw Man",
      desc: "A broke teenager who merges with his devil dog to become Chainsaw Man.",
      stats: 94,
      abilities: "Chainsaw transformation, regeneration, devil contracts",
      strength: "High pain tolerance, relentless survival instinct.",
      weakness: "Naivety, emotional manipulation.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Pochita",
      image: "/assets/Characters/pochita.png",
      role: "Chainsaw Devil",
      desc: "A mysterious devil who becomes Denji’s heart.",
      stats: 99,
      abilities: "Devil erasure, chainsaw manifestation",
      strength: "Reality-altering power, loyalty.",
      weakness: "Physical vulnerability in weakened state.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Makima",
      image: "/assets/Characters/makima.png",
      role: "Public Safety Devil Hunter / Control Devil",
      desc: "A manipulative authority figure with godlike control.",
      stats: 100,
      abilities: "Control, contracts, reality manipulation",
      strength: "Absolute dominance, long-term planning.",
      weakness: "Obsession with Chainsaw Man.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Power",
      image: "/assets/Characters/power.png",
      role: "Blood Fiend",
      desc: "A chaotic fiend driven by ego and loyalty to her cat.",
      stats: 90,
      abilities: "Blood manipulation, weapon creation",
      strength: "Aggression, creativity in combat.",
      weakness: "Impulsiveness, selfishness.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Aki Hayakawa",
      image: "/assets/Characters/aki.png",
      role: "Public Safety Devil Hunter",
      desc: "A serious hunter driven by revenge against devils.",
      stats: 92,
      abilities: "Fox Devil, Curse Devil, Future Devil",
      strength: "Discipline, tactical combat.",
      weakness: "Shortened lifespan due to contracts.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Katana Man",
      image: "/assets/Characters/katanaman.png",
      role: "Hybrid Devil",
      desc: "A vengeful hybrid seeking revenge against Denji.",
      stats: 91,
      abilities: "Katana transformation, enhanced speed",
      strength: "Deadly precision, durability.",
      weakness: "Tunnel-visioned hatred.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Reze",
      image: "/assets/Characters/reze.png",
      role: "Bomb Devil Hybrid",
      desc: "A charming assassin whose affection masks lethal intent.",
      stats: 95,
      abilities: "Explosion generation, hybrid regeneration",
      strength: "Deception, destructive power.",
      weakness: "Emotional conflict.",
      animeTitle: "Chainsaw Man",
    },
    {
      name: "Gun Devil",
      image: "/assets/Characters/gun_devil.png",
      role: "Primal Threat",
      desc: "A catastrophic devil responsible for mass destruction.",
      stats: 100,
      abilities: "Extreme speed, ballistic annihilation",
      strength: "Unmatched kill potential.",
      weakness: "Fragmented existence.",
      animeTitle: "Chainsaw Man",
    },
    // Spy x Family
    {
      name: "Loid Forger",
      image: "/assets/Characters/loid.png",
      role: "Master Spy / Agent Twilight",
      desc: "An elite spy forced to build a fake family to prevent war.",
      stats: 95,
      abilities: "Espionage, combat tactics, disguises",
      strength: "Strategic genius, adaptability.",
      weakness: "Emotional detachment.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Yor Forger",
      image: "/assets/Characters/yor.png",
      role: "Assassin / Thorn Princess",
      desc: "A deadly assassin pretending to be a normal housewife.",
      stats: 96,
      abilities: "Superhuman strength, assassination skills",
      strength: "Raw power, loyalty.",
      weakness: "Social awkwardness.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Anya Forger",
      image: "/assets/Characters/anya.png",
      role: "Telepathic Child",
      desc: "A mind-reading child determined to keep her family together.",
      stats: 80,
      abilities: "Telepathy",
      strength: "Emotional intelligence, insight.",
      weakness: "Childlike immaturity.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Bond Forger",
      image: "/assets/Characters/bond.png",
      role: "Precognitive Dog",
      desc: "A large, fluffy dog with the ability to see the future.",
      stats: 78,
      abilities: "Precognition",
      strength: "Loyalty, foresight.",
      weakness: "Limited understanding of humans.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Damian Desmond",
      image: "/assets/Characters/damian.png",
      role: "Eden Academy Student",
      desc: "A proud but insecure child seeking approval from his father.",
      stats: 75,
      abilities: "Political influence (family)",
      strength: "Determination, pride.",
      weakness: "Emotional immaturity.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Becky Blackbell",
      image: "/assets/Characters/becky.png",
      role: "Eden Academy Student",
      desc: "Anya’s loyal and outspoken best friend.",
      stats: 74,
      abilities: "Social influence",
      strength: "Confidence, loyalty.",
      weakness: "Naivety.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Donovan Desmond",
      image: "/assets/Characters/donovan.png",
      role: "Political Figure / Target",
      desc: "A reclusive politician whose actions could spark war.",
      stats: 88,
      abilities: "Strategic manipulation",
      strength: "Influence, secrecy.",
      weakness: "Paranoia.",
      animeTitle: "Spy x Family",
    },
    {
      name: "Yuri Briar",
      image: "/assets/Characters/yuri.png",
      role: "Secret Police Officer",
      desc: "Yor’s overprotective brother with extreme patriotism.",
      stats: 89,
      abilities: "Interrogation, endurance",
      strength: "Pain tolerance, loyalty.",
      weakness: "Obsessive behavior.",
      animeTitle: "Spy x Family",
    },
    // Death Note Characters 
    {
      name: "Light Yagami",
      image: "/assets/Characters/light.png",
      role: "Kira / Death Note User",
      desc: "A brilliant student who becomes judge, jury, and executioner of the world.",
      stats: 98,
      abilities: "Death Note usage, strategic manipulation",
      strength: "Genius intellect, psychological warfare.",
      weakness: "God complex, arrogance.",
      animeTitle: "Death Note",
    },
    {
      name: "L Lawliet",
      image: "/assets/Characters/l.png",
      role: "Detective",
      desc: "A legendary detective determined to expose Kira.",
      stats: 97,
      abilities: "Deductive reasoning, analytical intuition",
      strength: "Unmatched logic, deception.",
      weakness: "Social isolation.",
      animeTitle: "Death Note",
    },
    {
      name: "Ryuk",
      image: "/assets/Characters/ryuk.png",
      role: "Shinigami",
      desc: "A bored god of death who drops the Death Note into the human world.",
      stats: 90,
      abilities: "Shinigami abilities, Death Note knowledge",
      strength: "Immortality, detachment.",
      weakness: "Apathy.",
      animeTitle: "Death Note",
    },
    {
      name: "Misa Amane",
      image: "/assets/Characters/misa.png",
      role: "Second Kira",
      desc: "A devoted idol who aids Kira out of love and obsession.",
      stats: 85,
      abilities: "Death Note usage, Shinigami Eyes",
      strength: "Fan devotion, emotional leverage.",
      weakness: "Naivety, dependence on Light.",
      animeTitle: "Death Note",
    },
    {
      name: "Near",
      image: "/assets/Characters/near.png",
      role: "Detective / L’s Successor",
      desc: "A calm and methodical genius who continues L’s investigation.",
      stats: 96,
      abilities: "Strategic planning, probability analysis",
      strength: "Patience, logical foresight.",
      weakness: "Detached demeanor.",
      animeTitle: "Death Note",
    },
    {
      name: "Mello",
      image: "/assets/Characters/mello.png",
      role: "Rogue Investigator",
      desc: "A reckless but brilliant rival determined to surpass Near.",
      stats: 92,
      abilities: "Criminal tactics, intelligence",
      strength: "Bold decision-making.",
      weakness: "Impulsiveness.",
      animeTitle: "Death Note",
    },
  ];

for (const character of characterList) {
  const parentAnime = animeMap[character.animeTitle];

  if (!parentAnime) {
    console.warn(
      `No anime found for character "${character.name}" with animeTitle "${character.animeTitle}". Skipping.`
    );
    continue;
  }

  await prisma.character.upsert({
    where: { name: character.name },
    update: {
      image: character.image,
      role: character.role ?? null,
      desc: character.desc ?? null,
      stats: character.stats ?? null,
      abilities: character.abilities ?? null,
      strength: character.strength ?? null,
      weakness: character.weakness ?? null,
      anime: { connect: { id: parentAnime.id } },
    },
    create: {
      name: character.name,
      image: character.image,
      role: character.role ?? null,
      desc: character.desc ?? null,
      stats: character.stats ?? null,
      abilities: character.abilities ?? null,
      strength: character.strength ?? null,
      weakness: character.weakness ?? null,
      anime: { connect: { id: parentAnime.id } },
    },
  });
}

await seedAnimeStaffForAllAnime(createdAnimeRecords);

console.log("Seeded anime, characters, and staff credits");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

